// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzrsMYjcFzppjcgLNf2WWbke2QMT6jvoQ',
    appId: '1:875560978679:web:ca02d635717d7aa2082bf2',
    messagingSenderId: '875560978679',
    projectId: 'speedtrap-application',
    authDomain: 'speedtrap-application.firebaseapp.com',
    storageBucket: 'speedtrap-application.appspot.com',
    measurementId: 'G-6YKQN4ZPVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4C58pKkpn-9dKSuwIGsZucOY9ByZvrDU',
    appId: '1:875560978679:android:8dd908de8c26181a082bf2',
    messagingSenderId: '875560978679',
    projectId: 'speedtrap-application',
    storageBucket: 'speedtrap-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMyQUt9mKG6fnqeDWvKoSqRl7SeAiaPrs',
    appId: '1:875560978679:ios:c7df5da24e6bb9b7082bf2',
    messagingSenderId: '875560978679',
    projectId: 'speedtrap-application',
    storageBucket: 'speedtrap-application.appspot.com',
    iosClientId: '875560978679-6abd84dgdo47pj1cdl8j7ojjhffnincd.apps.googleusercontent.com',
    iosBundleId: 'com.example.kartingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMyQUt9mKG6fnqeDWvKoSqRl7SeAiaPrs',
    appId: '1:875560978679:ios:d1175ef82973f660082bf2',
    messagingSenderId: '875560978679',
    projectId: 'speedtrap-application',
    storageBucket: 'speedtrap-application.appspot.com',
    iosClientId: '875560978679-bfa2uh896fsvgsvfhi0do6ivbmoa00cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.kartingApplication.RunnerTests',
  );
}
